- name: Provisionar Infraestrutura na Azure
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    ansible_python_interpreter: "/mnt/c/Users/Cabelo/Documents/GitHub/ELA-DevOps/myenv/bin/python3"
  tasks:
    - name: Criar grupo de recursos
      azure.azcollection.azure_rm_resourcegroup:
        name: "MeuGrupoDeRecursos"
        location: "brazilsouth"  # Região brasileira

    - name: Criar rede virtual
      azure.azcollection.azure_rm_virtualnetwork:
        resource_group: "MeuGrupoDeRecursos"
        name: "MinhaVNet"
        location: "brazilsouth"  # Região brasileira
        address_prefixes:
          - "10.0.0.0/16"

    - name: Criar sub-rede na VNet
      azure.azcollection.azure_rm_subnet:
        resource_group: "MeuGrupoDeRecursos"
        virtual_network: "MinhaVNet"
        name: "MinhaSubrede"
        address_prefix: "10.0.1.0/24"

    - name: Criar IP público
      azure.azcollection.azure_rm_publicipaddress:
        resource_group: "MeuGrupoDeRecursos"
        name: "MinhaVNet-PublicIP"
        location: "brazilsouth"  # Região brasileira
        allocation_method: "Dynamic"

    - name: Criar interface de rede
      azure.azcollection.azure_rm_networkinterface:
        resource_group: "MeuGrupoDeRecursos"
        name: "MinhaVNet-NIC"
        location: "brazilsouth"  # Região brasileira
        virtual_network: "MinhaVNet"
        subnet_name: "MinhaSubrede"
        public_ip_address_name: "MinhaVNet-PublicIP"

    - name: Criar máquina virtual com disco gerenciado
      azure.azcollection.azure_rm_virtualmachine:
        resource_group: "MeuGrupoDeRecursos"
        name: "MinhaVM"
        location: "brazilsouth"  # Região brasileira
        vm_size: "Standard_D1"
        admin_username: "adminuser"
        admin_password: "Senha@Segura123"
        image:
          offer: "0001-com-ubuntu-server-focal"
          publisher: "Canonical"
          sku: "20_04-lts-gen2"
          version: "latest"
        managed_disk_type: "Standard_LRS"
        network_interface_names:
          - "MinhaVNet-NIC"
