- name: Provisionar Infraestrutura na Azure
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    ansible_python_interpreter: "/mnt/c/Users/Cabelo/Documents/GitHub/ELA-DevOps/myenv/bin/python3"
  
  tasks:
    - name: Criar grupo de recursos
      azure.azcollection.azure_rm_resourcegroup:
        name: "MeuGrupoDeRecursos"
        location: "brazilsouth"

    - name: Verificar se a VNet já existe
      azure.azcollection.azure_rm_virtualnetwork_info:
        resource_group: "MeuGrupoDeRecursos"
        name: "MinhaVNet"
      register: vnet_facts
      ignore_errors: yes

    - name: Criar rede virtual, se não existir
      azure.azcollection.azure_rm_virtualnetwork:
        resource_group: "MeuGrupoDeRecursos"
        name: "MinhaVNet"
        location: "brazilsouth"
        address_prefixes:
          - "10.0.0.0/16"
      when: vnet_facts.failed

    - name: Criar sub-rede na VNet, se a VNet foi criada
      azure.azcollection.azure_rm_subnet:
        resource_group: "MeuGrupoDeRecursos"
        virtual_network: "MinhaVNet"
        name: "MinhaSubrede"
        address_prefix: "10.0.1.0/24"
      when: vnet_facts is defined and vnet_facts.failed

    - name: Criar IP público
      azure.azcollection.azure_rm_publicipaddress:
        resource_group: "MeuGrupoDeRecursos"
        name: "MinhaVNet-PublicIP"
        location: "brazilsouth"
        allocation_method: "Dynamic"

    - name: Criar interface de rede
      azure.azcollection.azure_rm_networkinterface:
        resource_group: "MeuGrupoDeRecursos"
        name: "MinhaVNet-NIC"
        location: "brazilsouth"
        virtual_network: "MinhaVNet"
        subnet_name: "MinhaSubrede"
        public_ip_address_name: "MinhaVNet-PublicIP"
      when: vnet_facts is defined and vnet_facts.failed

    - name: Criar máquina virtual com disco gerenciado
      azure.azcollection.azure_rm_virtualmachine:
        resource_group: "MeuGrupoDeRecursos"
        name: "MinhaVM"
        location: "brazilsouth"
        vm_size: "Standard_D1"
        admin_username: "adminuser"
        admin_password: "Senha@Segura123"
        image:
          offer: "0001-com-ubuntu-server-focal"
          publisher: "Canonical"
          sku: "20_04-lts-gen2"
          version: "latest"
        managed_disk_type: "Standard_LRS"
        network_interface_names:
          - "MinhaVNet-NIC"
      when: vnet_facts is defined and vnet_facts.failed
