name: Build and Test Docker - Dev

on:
  push:
    branches: [Dev]
  pull_request:
    branches: [Dev]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Cache pip dependencies
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build Docker image
      run: |
        docker build -t mediapipe-eye-detection:dev .

    - name: Run tests in Docker container
      run: |
        docker run --rm mediapipe-eye-detection:dev bash -c "pip install -r requirements.txt && python -m unittest discover -s tests"

    - name: Lint code (optional)
      run: |
        pip install flake8
        flake8 . --exit-zero
